cpmaddpackage(
    NAME
    glm
    GITHUB_REPOSITORY
    g-truc/glm
    GIT_TAG
    1.0.2
    OPTIONS
    "GLM_BUILD_TESTS OFF"
    "GLM_BUILD_INSTALL OFF"
    "GLM_ENABLE_CXX_20 ON"
    "GLM_ENABLE_LANG_EXTENSIONS ON")
