name: CMake Multi-Platform CI/CD

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build-package:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        build_type: [Release]
        compiler: [clang]
        include:
          - os: ubuntu-latest
            compiler: clang
            c_compiler: clang
            cxx_compiler: clang++
          - os: windows-latest
            compiler: clang
            c_compiler: clang-cl
            cxx_compiler: clang-cl

    steps:
      - uses: actions/checkout@v4

      - name: Install LLVM (Windows)
        if: matrix.os == 'windows-latest'
        run: choco install ninja

      - name: Install Linux deps
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y libgl-dev libgles-dev build-essential git make \
            pkg-config cmake ninja-build gnome-desktop-testing libasound2-dev libpulse-dev \
            libaudio-dev libjack-dev libsndio-dev libx11-dev libxext-dev \
            libxrandr-dev libxcursor-dev libxfixes-dev libxi-dev libxss-dev \
            libxkbcommon-dev libdrm-dev libgbm-dev libgl1-mesa-dev libgles2-mesa-dev \
            libegl1-mesa-dev libdbus-1-dev libibus-1.0-dev libudev-dev fcitx-libs-dev

      - name: Configure CMake
        run: cmake --workflow --preset clang-full

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.os }}-${{ matrix.compiler }}-package
          path: |
            build/clang/*.tar.gz
            build/clang/*.rpm
            build/clang/*.zip
