name: cmake-multiplatform-workflow

on:
  push:
    branches: ["main"]
    paths:
      - 'src/**'
      - 'include/**'
      - 'cmake/**'
      - '**/*.cmake'
      - '**/*.cpp'
      - '**/*.hpp'
      - '**/*.c'
      - '**/*.h'
      - '**/*.cxx'
      - '**/*.hxx'
      - 'CMakeLists.txt'
      - '**/*CMakeLists*.txt'
      - '**/*CMakePresets.json'
      - '.github/workflows/**'
  pull_request:
    branches: ["main"]
    paths:
      - 'src/**'
      - 'include/**'
      - 'cmake/**'
      - '**/*.cmake'
      - '**/*.cpp'
      - '**/*.hpp'
      - '**/*.c'
      - '**/*.h'
      - '**/*.cxx'
      - '**/*.hxx'
      - 'CMakeLists.txt'
      - '**/*CMakeLists*.txt'
      - '**/CMakePresets.json'
      - '.github/workflows/**'

jobs:
  build-package:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        include:
          - os: ubuntu-latest
            preset: clang-full
          - os: windows-latest
            preset: msvc-full

    steps:
      - uses: actions/checkout@v4

      - name: Install Linux deps
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update -qq
          sudo apt-get install -y --no-install-recommends \
          libwayland-dev \
          libxkbcommon-dev \
          libegl1-mesa-dev \
          libgles2-mesa-dev \
          libgl1-mesa-dev \
          libdbus-1-dev \
          libudev-dev \
          libasound2-dev \
          ninja-build \
          clang

      - name: Configure CMake
        run: cmake --workflow --preset ${{ matrix.preset }}

      - name: Upload ZIP artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.os }}-${{ matrix.preset }}-zip
          path: build/*/*.zip
          if-no-files-found: ignore

      - name: Upload TAR.GZ artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.os }}-${{ matrix.preset }}-tar-gz
          path: build/*/*.tar.gz
          if-no-files-found: ignore

      - name: Upload RPM artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.os }}-${{ matrix.preset }}-rpm
          path: build/*/*.rpm
          if-no-files-found: ignore
