name: CMake Multi-Platform CI/CD

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build-package:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        include:
          - os: ubuntu-latest
            preset: clang-full
          - os: windows-latest
            preset: msvc-full

    steps:
      - uses: actions/checkout@v4

      - name: Install Linux deps
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update -qq
          sudo apt-get install -y --no-install-recommends \
          libwayland-dev \
          libxkbcommon-dev \
          libegl1-mesa-dev \
          libgles2-mesa-dev \
          libgl1-mesa-dev \
          libdbus-1-dev \
          libudev-dev \
          libasound2-dev \
          ninja-build \
          clang

      - name: Configure CMake
        run: cmake --workflow --preset ${{ matrix.preset }}

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.os }}-${{ matrix.preset }}-package
          path: |
            build/clang/*.tar.gz
            build/clang/*.rpm
            build/clang/*.zip
