name: doxygen-docs
# todo: make it be only docs target, no other tools to avoid warnings (as dev tools)

on:
  release:
    types: [published]

jobs:
  build-docs:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # needed for git tags/version info

      - name: Install docs deps
        run: |
          sudo apt-get update -qq
          sudo apt-get install -y --no-install-recommends \
          doxygen \
          graphviz \
          libwayland-dev \
          libxkbcommon-dev \
          libegl1-mesa-dev \
          libgles2-mesa-dev \
          libgl1-mesa-dev \
          libdbus-1-dev \
          libudev-dev \
          libasound2-dev \
          ninja-build \
          clang

      - name: Configure CMake for docs
        run: cmake --preset clang -DENABLE_DEV_TOOLS=ON

      - name: Build CMake for docs
        run: cmake --build --preset clang

      - name: Upload docs artifacts
        uses: actions/upload-artifact@v4
        with:
          name: documentation
          path: |
            build/**/generated-docs/**
